apiVersion: apps/v1
kind: Deployment
metadata: 
  name: posts-depl
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: posts
  template:
    metadata:
      labels:
        app: posts 
    spec:
      containers:
        - name: posts
          image: sushantskb/microservices:posts-latest # generally here it should be microservices:latest but since I am maintaining multiple versions of the same microservice, I have used a different tag for each version....